version: '3.7'

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "16686:16686" # Jaeger UI
    environment:
      - OTEL_TRACES_SAMPLER=always_off
      - LOG_LEVEL=debug
  
  service-a:
    build:
      context: ./nestjs-project-1
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs-project-1:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - JAEGER_AGENT_URL=http://jaeger:4317
      - JAEGER_SERVICE_NAME=service-a
      - SERVICE_B_URL=http://service-b:3000
      - SERVICE_C_URL=http://service-c:3000
    depends_on:
      - jaeger
  service-b:
    build:
      context: ./nestjs-project-2
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "3001:3000"
    volumes:
      - ./nestjs-project-2:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - JAEGER_AGENT_URL=http://jaeger:4317
      - JAEGER_SERVICE_NAME=service-b
      - SERVICE_A_URL=http://service-a:3000
      - SERVICE_C_URL=http://service-c:3000
    depends_on:
      - jaeger
  service-c:
    build:
      context: ./nestjs-project-3
      dockerfile: Dockerfile
    container_name: service-c
    ports:
      - "3002:3000"
    volumes:
      - ./nestjs-project-3:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - JAEGER_AGENT_URL=http://jaeger:4317
      - JAEGER_SERVICE_NAME=service-c
      - SERVICE_A_URL=http://service-a:3000
      - SERVICE_B_URL=http://service-b:3000
    depends_on:
      - jaeger
  client:
    build:
      context: ./react-demo-tracing
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_JAEGER_AGENT_URL=http://jaeger:4317
      - REACT_APP_JAEGER_SERVICE_NAME=client
    volumes:
      - ./react-demo-tracing:/app
      - /app/node_modules
    command: pnpm dev
   
